defmodule LLMDB.Application do
  @moduledoc """
  OTP Application for LLMDB.

  Automatically loads the pre-built snapshot on application start.
  The snapshot is generated by `mix llm_db.build` and packaged
  with the release.
  """

  use Application

  @impl true
  def start(_type, _args) do
    with :ok <- load_catalog() do
      Supervisor.start_link([], strategy: :one_for_one, name: LLMDB.Supervisor)
    end
  end

  defp load_catalog do
    LLMDB.Dotenv.load!()
    _ = LLMDB.Generated.ValidModalities.list()

    if Application.get_env(:llm_db, :skip_packaged_load, false) do
      :ok
    else
      case LLMDB.load() do
        {:ok, _snapshot} -> :ok
        {:error, reason} -> {:error, reason}
      end
    end
  end
end
